services:
  dev:
    image: deiiulpgc/deii-frontend:app-dev
    container_name: front_cont

    working_dir: /frontend
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public

    ports:
      - 3000:3000
    
    command: npm run dev
    
    environment:
      - SERVER_PORT=8080
  
  storybook:
    image: deiiulpgc/deii-frontend:app-dev
    container_name: storybook_cont

    working_dir: /frontend
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public

    ports:
      - 8008:8008
    
    command: npm run storybook

    
  pocketbase:
    image: deiiulpgc/deii-frontend:pocketbase
    container_name: pb-cont
    restart: unless-stopped
    #volumes:

    working_dir: /pocketbase

    ports:
      - 8090:8090
    
    command: ./pocketbase serve --http="0.0.0.0:8090"

    