import { ChakraProvider } from "@chakra-ui/react"
import { ThemeProvider } from "@components/providers/ThemeProvider"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body style={{ backgroundColor: "#f5f5f5" }}>
				<ThemeProvider>{children}</ThemeProvider>
			</body>
		</html>
	)
}
