name: Formatter and Linting
on: [pull_request]

jobs: 
  formatting: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci 

      - name: Run formatter
        run: npm run format
